server:
  port: 9003

spring:
  application:
    name: stock-v2-service
  cloud:
    zookeeper:
      discovery:
        enabled: true
      connect-string: lsz.env.com:2181
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://lsz.env.com:3307/stock
    username: root
    password: 123456


  kafka:
    bootstrap-servers: lsz.env.com:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: demo
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false
      auto-offset-reset: earliest
    listener:
      ack-mode: manual_immediate


mybatis:
  mapperLocations: classpath:mapper/*.xml
logging:
  level:
    com.lsz: debug
