server:
  port: 8006
spring:
  application:
    name: consul-provider-payment

  cloud:
    # consul注册中心
    consul:
      host: 192.168.2.102
      port: 8500
      discovery:
        service-name: ${spring.application.name}
