server:
  port: 8401

spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.106:8848 #Nacos服务注册中心地址
    sentinel:
      transport:
        dashboard: 192.168.0.106:8858 #配置Sentinel dashboard地址
        port: 8719
        client-ip: 192.168.0.107 # docker启动需要此配置项
      # 还需在nacos中新建配置，配置内容 sentinel-datasource-nacos.json
      datasource:
        ds1:
          nacos:
            server-addr: 192.168.0.106:8848
            dataId: cloudalibaba-sentinel-service
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow

management:
  endpoints:
    web:
      exposure:
        include: '*'


