server:
  port: 80
spring:
  application:
    name: consul-consumer-order

  # consul注册中心
  cloud:
    consul:
      host: 192.168.2.102
      port: 8500
      discovery:
        service-name: ${spring.application.name}