server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment_routh           # 路由ID，没有固定规则，要求唯一
          uri: http://localhost:8001  # 匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**    # 断言，路径相匹配的进行路由

        - id: payment_routh2
          uri: http://localhost:8001
          predicates:
            - Path=/payment/lb/**
      enabled: true
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
    # 注册中心
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #配置nacos地址
        namespace: default
    sentinel:
      transport:
        dashboard: 127.0.0.1:8060 #配置Sentinel dashboard地址
#        port: 8719
#        client-ip: 127.0.0.1 # docker启动需要此配置项

management:
  endpoints:
    web:
      exposure:
        include: '*'